apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatgpt-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatgpt-pod
  template:
    metadata:
      labels:
        app: chatgpt-pod
    spec:
      containers:
      - name: mychatgptcontainer
        image: kogtikovnikita/chatgpt-project:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
        env:
        - name: OPENAI_API
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: API_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: mysvc-v2
spec:
  type: LoadBalancer
  selector:
    app: chatgpt-pod
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
    protocol: TCP

